
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var testMetadata = {
  "n": "TestEntities",
  "m": [
    {
      "n": "Beetle.Client.Models.Address, Beetle.Client",
      "s": "Address",
      "q": "Entities",
      "t": "Entity",
      "b": "Entity",
      "k": [
        "Id"
      ],
      "d": [
        {
          "n": "Country",
          "t": "string",
          "i": true,
          "v": []
        },
        {
          "n": "City",
          "r": "City",
          "l": "City",
          "t": "string",
          "i": true,
          "v": [
            {
              "t": "mi",
              "m": "City length should be more than 2.",
              "a": [
                2
              ]
            },
            {
              "t": "ma",
              "m": "City length cannot be more than 10.",
              "a": [
                10
              ]
            }
          ]
        },
        {
          "n": "PostalCode",
          "r": "PostalCode",
          "l": "Postal code",
          "t": "string",
          "i": true,
          "v": [
            {
              "t": "sl",
              "m": "Postal code field must be at least 2 and at most 6 characters long.",
              "r": "StringLength",
              "a": [
                2,
                6
              ]
            },
            {
              "t": "re",
              "m": "Postal code is required, please fill.",
              "a": [
                false
              ]
            },
            {
              "t": "po",
              "m": "The field Postal code is invalid."
            }
          ]
        },
        {
          "n": "DoorNumber",
          "r": "DoorNumber",
          "l": "Door number",
          "t": "int",
          "i": true,
          "v": [
            {
              "t": "ra",
              "m": "Door number field must be bigger than 100000 and smaller than 1000.",
              "r": "Range",
              "a": [
                1000,
                100000
              ]
            }
          ]
        },
        {
          "n": "Extra",
          "l": "Extra information",
          "t": "string",
          "i": true,
          "v": [
            {
              "t": "ea",
              "m": "The Extra information field is not a valid e-mail address."
            },
            {
              "t": "ti",
              "m": "The field Extra information is invalid."
            },
            {
              "t": "co",
              "m": "Extra information value must be equal to Extra2.",
              "a": [
                "Extra2"
              ]
            },
            {
              "t": "cc",
              "m": "The Extra information field is not a valid credit card number."
            },
            {
              "t": "rx",
              "m": "Extra information must be Fibonacci number.",
              "a": [
                "1|2|3|5|8"
              ]
            },
            {
              "t": "ur",
              "m": "The Extra information field is not a valid fully-qualified http, https, or ftp URL."
            },
            {
              "t": "ph",
              "m": "The Extra information field is not a valid phone number."
            }
          ]
        },
        {
          "n": "Extra2",
          "l": "Extra information 2",
          "t": "string",
          "i": true,
          "v": []
        }
      ],
      "r": [
        {
          "n": "Companies",
          "t": "Company",
          "a": "FK_Company_Address",
          "f": [],
          "v": []
        }
      ],
      "x": []
    },
    {
      "n": "Beetle.Client.Models.Company, Beetle.Client",
      "s": "Company",
      "q": "Entities",
      "t": "Entity",
      "b": "NamedEntity",
      "k": [
        "Id"
      ],
      "d": [
        {
          "n": "AddressId",
          "t": "guid",
          "i": true,
          "v": []
        },
        {
          "n": "CompanyNo",
          "t": "string",
          "v": []
        },
        {
          "n": "CompanyType",
          "t": "CompanyType",
          "e": true,
          "v": []
        }
      ],
      "r": [
        {
          "n": "Address",
          "t": "Address",
          "s": true,
          "a": "FK_Company_Address",
          "f": [
            "AddressId"
          ],
          "v": []
        }
      ],
      "x": []
    },
    {
      "n": "Beetle.Client.Models.Entity, Beetle.Client",
      "s": "Entity",
      "q": "Entities",
      "k": [
        "Id"
      ],
      "d": [
        {
          "n": "Id",
          "t": "guid",
          "v": []
        },
        {
          "n": "ShortId",
          "t": "int",
          "g": "I",
          "v": []
        },
        {
          "n": "UserNameCreate",
          "t": "string",
          "i": true,
          "v": []
        },
        {
          "n": "TimeCreate",
          "t": "date",
          "v": []
        },
        {
          "n": "IsCanceled",
          "t": "boolean",
          "i": true,
          "v": []
        }
      ],
      "r": [],
      "x": []
    },
    {
      "n": "Beetle.Client.Models.NamedEntity, Beetle.Client",
      "s": "NamedEntity",
      "q": "Entities",
      "t": "Entity",
      "b": "Entity",
      "k": [
        "Id"
      ],
      "d": [
        {
          "n": "NamedEntityTypeId",
          "t": "guid",
          "v": []
        },
        {
          "n": "Name",
          "t": "string",
          "i": true,
          "v": []
        },
        {
          "n": "Description",
          "t": "string",
          "i": true,
          "v": []
        },
        {
          "n": "NamedEntityId_Parent",
          "t": "guid",
          "i": true,
          "v": []
        }
      ],
      "r": [
        {
          "n": "NamedEntityType",
          "t": "NamedEntityType",
          "s": true,
          "a": "FK_NamedEntity_NamedEntityType",
          "f": [
            "NamedEntityTypeId"
          ],
          "v": []
        },
        {
          "n": "Children",
          "t": "NamedEntity",
          "a": "FK_NamedEntity_NamedEntity_Parent",
          "f": [],
          "v": []
        },
        {
          "n": "Parent",
          "t": "NamedEntity",
          "s": true,
          "a": "FK_NamedEntity_NamedEntity_Parent",
          "f": [
            "NamedEntityId_Parent"
          ],
          "v": []
        }
      ],
      "x": []
    },
    {
      "n": "Beetle.Client.Models.NamedEntityType, Beetle.Client",
      "s": "NamedEntityType",
      "q": "NamedEntityTypes",
      "k": [
        "Id"
      ],
      "d": [
        {
          "n": "Id",
          "t": "guid",
          "v": []
        },
        {
          "n": "Name",
          "t": "string",
          "v": []
        }
      ],
      "r": [
        {
          "n": "NamedEntities",
          "t": "NamedEntity",
          "a": "FK_NamedEntity_NamedEntityType",
          "f": [],
          "v": []
        }
      ],
      "x": []
    },
    {
      "n": "Beetle.Client.Models.Order, Beetle.Client",
      "s": "Order",
      "q": "Orders",
      "k": [
        "Id"
      ],
      "d": [
        {
          "n": "Id",
          "t": "int",
          "g": "I",
          "v": []
        },
        {
          "n": "OrderNo",
          "t": "string",
          "v": []
        },
        {
          "n": "Price",
          "t": "number",
          "p": 18,
          "s": 3,
          "v": []
        }
      ],
      "r": [
        {
          "n": "OrderDetails",
          "t": "OrderDetail",
          "a": "FK_Order_OrderDetail",
          "c": true,
          "f": [],
          "v": []
        }
      ],
      "x": []
    },
    {
      "n": "Beetle.Client.Models.OrderDetail, Beetle.Client",
      "s": "OrderDetail",
      "q": "OrderDetails",
      "k": [
        "Id"
      ],
      "d": [
        {
          "n": "Id",
          "t": "int",
          "g": "I",
          "v": []
        },
        {
          "n": "OrderId",
          "t": "int",
          "v": []
        },
        {
          "n": "ProductNo",
          "t": "string",
          "i": true,
          "v": []
        }
      ],
      "r": [
        {
          "n": "Order",
          "t": "Order",
          "s": true,
          "a": "FK_Order_OrderDetail",
          "f": [
            "OrderId"
          ],
          "v": []
        }
      ],
      "x": []
    }
  ],
  "e": [
    {
      "n": "CompanyType",
      "m": [
        {
          "n": "Customer",
          "v": 1
        },
        {
          "n": "Supplier",
          "v": 2
        }
      ]
    }
  ]
};
