//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beetle.Client.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(AddressMetadata))]
    public partial class Address : Entity
    {
        public Address()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public string Country { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> DoorNumber { get; set; }
        public string Extra { get; set; }
        public string Extra2 { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
    }
    
    public partial class AddressMetadata { }
}
