//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beetle.Client.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(EntityMetadata))]
    public partial class Entity
    {
        public System.Guid Id { get; set; }
        public int ShortId { get; set; }
        public string UserNameCreate { get; set; }
        public System.DateTime TimeCreate { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
    }
    
    public partial class EntityMetadata { }
}
