//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beetle.Client.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(NamedEntityMetadata))]
    public partial class NamedEntity : Entity
    {
        public NamedEntity()
        {
            this.Children = new HashSet<NamedEntity>();
        }
    
        public System.Guid NamedEntityTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> NamedEntityId_Parent { get; set; }
    
        public virtual NamedEntityType NamedEntityType { get; set; }
        public virtual ICollection<NamedEntity> Children { get; set; }
        public virtual NamedEntity Parent { get; set; }
    }
    
    public partial class NamedEntityMetadata { }
}
