//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beetle.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beetle.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change query type for non-generic queries..
        /// </summary>
        internal static string CannotChangeQueryType {
            get {
                return ResourceManager.GetString("CannotChangeQueryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any key for &apos;{0}&apos;..
        /// </summary>
        internal static string CannotFindAnyKey {
            get {
                return ResourceManager.GetString("CannotFindAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find metadata for &apos;{0}&apos;..
        /// </summary>
        internal static string CannotFindMetadata {
            get {
                return ResourceManager.GetString("CannotFindMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find public &apos;{0}&apos; instance field or property..
        /// </summary>
        internal static string CannotFindPublicInstanceFieldOrProperty {
            get {
                return ResourceManager.GetString("CannotFindPublicInstanceFieldOrProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find tracker info..
        /// </summary>
        internal static string CannotFindTrackerInfo {
            get {
                return ResourceManager.GetString("CannotFindTrackerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find type information for &apos;{0}&apos;..
        /// </summary>
        internal static string CannotFindTypeInformation {
            get {
                return ResourceManager.GetString("CannotFindTypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get generated values, when EntityType is not available in EntityBag, Metadata parameter must be given..
        /// </summary>
        internal static string CannotGetGeneratedValues {
            get {
                return ResourceManager.GetString("CannotGetGeneratedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save entity with state &apos;{0}&apos;..
        /// </summary>
        internal static string CannotSaveEntityWithState {
            get {
                return ResourceManager.GetString("CannotSaveEntityWithState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set read-only &apos;{0}&apos; property..
        /// </summary>
        internal static string CannotSetReadOnlyProperty {
            get {
                return ResourceManager.GetString("CannotSetReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection cannot be null..
        /// </summary>
        internal static string ConnectionCannotBeNull {
            get {
                return ResourceManager.GetString("ConnectionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete command affected an unexpected number of rows. Entities may have been modified or deleted since last read..
        /// </summary>
        internal static string DeleteAffectedUnexpectedNumberOfRows {
            get {
                return ResourceManager.GetString("DeleteAffectedUnexpectedNumberOfRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity and ClientEntity must be same type to compare..
        /// </summary>
        internal static string EntityAndClientEntityMustBeSameTypeToCompare {
            get {
                return ResourceManager.GetString("EntityAndClientEntityMustBeSameTypeToCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type cannot be found for &apos;{0}&apos;..
        /// </summary>
        internal static string EntityTypeCannotBeFound {
            get {
                return ResourceManager.GetString("EntityTypeCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert command affected an unexpected number of rows..
        /// </summary>
        internal static string InsertAffectedUnexpectedNumberOfRows {
            get {
                return ResourceManager.GetString("InsertAffectedUnexpectedNumberOfRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid group by expression: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidGroupByExpression {
            get {
                return ResourceManager.GetString("InvalidGroupByExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property length cannot exceed {1}..
        /// </summary>
        internal static string MaxLenError {
            get {
                return ResourceManager.GetString("MaxLenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original value property could not be found for &apos;{0}&apos;..
        /// </summary>
        internal static string OriginalValuePropertyCouldNotBeFound {
            get {
                return ResourceManager.GetString("OriginalValuePropertyCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1 property is required..
        /// </summary>
        internal static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result count exceeded the allowed limit..
        /// </summary>
        internal static string ResultCountExceeded {
            get {
                return ResourceManager.GetString("ResultCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type could not be found: {0}.
        /// </summary>
        internal static string TypeCouldNotBeFound {
            get {
                return ResourceManager.GetString("TypeCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown beetle query executer parameter: &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownBeetleQueryExecuterParameter {
            get {
                return ResourceManager.GetString("UnknownBeetleQueryExecuterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown beetle query parameter: &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownBeetleQueryParameter {
            get {
                return ResourceManager.GetString("UnknownBeetleQueryParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update command affected an unexpected number of rows. Entities may have been modified or deleted since last read..
        /// </summary>
        internal static string UpdateAffectedUnexpectedNumberOfRows {
            get {
                return ResourceManager.GetString("UpdateAffectedUnexpectedNumberOfRows", resourceCulture);
            }
        }
    }
}
